### ISSUE TITLE
editMessageText with inline_message_id

### ISSUE THREAD

**Issue by FDeghy** [nutgram/nutgram#149]
When i use edit Inline message with inline_message_id and not chat_id & message_id, I will get : Bad Request: chat not found.

$bot->editMessageText("Text", ['inline_message_id' => $bot->chosenInlineResult()->inline_message_id]);

Please remove chat_id & message_id from json array when they are Null.

**Comment by SergiX44** [comment]
> When i use edit Inline message with inline_message_id and not chat_id & message_id, I will get : Bad Request: chat not found.
> 
> $bot->editMessageText("Text", ['inline_message_id' => $bot->chosenInlineResult()->inline_message_id]);
> 
> Please remove chat_id & message_id from json array when they are Null.

The PR #150 should fix that behavior when using that inside a handler context

Your example should work now, but also should automatically take the `inline_message_id` from the context and calling
```php 
$bot->editMessageText('Text');
```
Should also work
