### ISSUE TITLE
[FEATURE] Send bulk message

### ISSUE THREAD

**Issue by flakka2022** [nutgram/nutgram#161]
### Is your feature request related to a problem? Please describe.

Send bulk message to huge number of users and return result of success and fails .

**Comment by flakka2022** [comment]
hi again . i found a example of this in https://github.com/badfarm/zanzara/wiki#bulk-messaging

**Comment by Lukasss93** [comment]
https://github.com/nutgram/nutgram/discussions/179

**Comment by flakka2022** [comment]
still waiting
