### ISSUE TITLE
[FEATURE] Message Chunk

### ISSUE THREAD

**Issue by DanielSpravtsev** [nutgram/nutgram#173]
### Is your feature request related to a problem? Please describe.

Reaching message text limit will throw Telegram HTTP exception

### Describe the solution you'd like

Send multiple telegram messages instead off falling to exception

### Describe alternatives you've considered

There is a great and simple solution in Telegram Notification Channel

**Sending message**
https://github.com/laravel-notification-channels/telegram/blob/76299fa06f48cb175e17ea951ccf3b185329a1ac/src/TelegramChannel.php#L70

**Message chunk implementation**
https://github.com/laravel-notification-channels/telegram/blob/76299fa06f48cb175e17ea951ccf3b185329a1ac/src/TelegramChannel.php#L128

**Comment by flakka2022** [comment]
do not cut words in spliting pls
