### ISSUE TITLE
[BUG] Correct conversation recognition

### ISSUE THREAD

**Issue by flakka2022** [nutgram/nutgram#183]
### Describe the bug

Unfortunately, if a user being in conversation in two bots with the same source code on the same server ( using same cache adapter ) ,
 **there will be Confluence/interference because the chat_id and user_id is same !!!**

### To Reproduce

just run two bots with same code and same server ( same cache adapter ) then start a conversation !
Because bot_id is not used in conversation step set and recovery, you will see Confluence.

### Expected behavior

add bot_id in conversations !

**Comment by SergiX44** [comment]
First of all, different bots should use different caches for this exact reason, with a filesystem cache different folders, with redis different databases or prefixes, with relational db different databases, ...
It is not just a matter of conversations but also the global and user data.
A fix can be worked out, but I strongly suggest separating data of different bots anyway
