### ISSUE TITLE
[BUG] onMessage() is not working

### ISSUE THREAD

**Issue by gensart-ai** [nutgram/nutgram#188]
### Describe the bug

I have a code in CodeIgniter based there below :

```
<?php

namespace App\Controllers;

use SergiX44\Nutgram\Nutgram;
use SergiX44\Nutgram\RunningMode\Webhook;

class Home extends BaseController
{
    public function index()
    {
        $token = 'mybottoken';
        $stelapi = new Nutgram($token);
        $stelapi->setRunningMode(Webhook::class);

        $stelapi->onMessage(function(Nutgram $nutapi) {
            $nutapi->sendMessage('i heard that');
        });

        $stelapi->run();
    }
}
```

When i call `onText()` it works, and then when i try `onMessageType('photo',$callable)` it works too (with message type is photo, i mean i sent a photo),

but when i try with text with `onMessage($callable)` it looks like it doesn't work, the bot didn't send any message, and `onMessage(MessageType::TEXT, $callable)` doesn't work too. Why ? idk if its from me or a bug. thankyou.

### To Reproduce

explained above.

### Expected behavior

When `onMessage()` called / i texted something in my Telegram bot, it should say back with `i heard that`

**Comment by SergiX44** [comment]
I'm sorry but I'm not able to reproduce it, I've literally copy pasted your code snipped but its working. Can you try with Polling mode in a console command and see if its working? Which version of Nutgram you have? The Webhook class takes the JSON from `php://input`, are you sure that maybe CI4 is messing with the input streams?

**Comment by gensart-ai** [comment]
But can you show me an example of "worked" code ? with your system details ?

Currently in my project, i used :
~ Codeigniter 4.2.3
~ Nutgram i installed via (composer require nutgram/nutgram) i think it 3.5.1

I really confused because `onText()` work but `onMessage()` no.

**Comment by gensart-ai** [comment]
I give you my bot token : `5504059543:AAGAtBnHGZgJmU3wcBfeINhZSxIYCR_405w`

Really, on me with my details above it still didn't work
Below is Nutgram composer.json i installed with `composer require nutgram/nutgram`
```
{
    "name": "nutgram/nutgram",
    "description": "The Telegram bot library that doesn't drive you nuts",
    "keywords": [
        "nutgram",
        "telegram",
        "bot",
        "api",
        "library",
        "framework",
        "laravel"
    ],
    "homepage": "https://github.com/SergiX44/Nutgram",
    "license": "MIT",
    "authors": [
        {
            "name": "Sergio Brighenti",
            "email": "sergio@brighenti.me",
            "role": "Developer"
        },
        {
            "name": "Luca Patera",
            "email": "luca.patera@outlook.it",
            "role": "Developer"
        }
    ],
    "require": {
        "php": ">=8.0",
        "ext-json": "*",
        "guzzlehttp/guzzle": "^7.2",
        "illuminate/macroable": "^8.0|^9.0",
        "league/container": "^4.2",
        "nutgram/hydrator": "^2.0",
        "opis/closure": "^3.6",
        "psr/simple-cache": "^1.0|^2.0|^3.0"
    },
    "require-dev": {
        "ext-reflection": "*",
        "illuminate/testing": "^8.0|^9.0",
        "orchestra/testbench": "^6.0|^7.0",
        "pestphp/pest": "^1.1",
        "pestphp/pest-plugin-mock": "^1.0",
        "roave/security-advisories": "dev-latest",
        "vimeo/psalm": "^4.11"
    },
    "autoload": {
        "psr-4": {
            "SergiX44\\Nutgram\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "SergiX44\\Nutgram\\Tests\\": "tests/"
        }
    },
    "scripts": {
        "test": "vendor/bin/pest",
        "psalm": "vendor/bin/psalm"
    },
    "config": {
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "extra": {
        "laravel": {
            "providers": [
                "SergiX44\\Nutgram\\NutgramServiceProvider"
            ]
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

**Comment by SergiX44** [comment]
![image](https://user-images.githubusercontent.com/4172890/183897148-776bd539-f57d-45be-ba72-12f3285ec7d9.png)

**Comment by SergiX44** [comment]
Please dont post private info, the bot token does not help with debugging.

**Comment by gensart-ai** [comment]
Oh ya i forgot, im using ngrok too for webhooking to Telegram (just for development).
Is that having chance to be a problem ?

**Comment by gensart-ai** [comment]
> ![image](https://user-images.githubusercontent.com/4172890/183897148-776bd539-f57d-45be-ba72-12f3285ec7d9.png)

its quite same with my code. May my CI 4 having a problem ?

**Comment by gensart-ai** [comment]
well im gonna try one more again
from composer nutgram/nutgram

**Comment by fauzipadlaw** [comment]
Hi, I'm using Laravel, it seems this bug happens on latest version, onMessage does not work.
