### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by v8hid** [nutgram/nutgram#190]
### Describe the bug

Hi, I found a bug in this framework
I use Nutgram latest version on Laravel 9
I noticed that sometimes my bot is not working and Telegram showing 500 internal server error on Webhook request attempt, I logged the input from Webhook when error occurred;
**this is the error :** 
`SergiX44\Nutgram\Telegram\Exceptions\TelegramException: Bad Request: chat not found in file /var/www/html/vendor/nutgram/nutgram/src/Telegram/Client.php on line 287`  
**and this is the input from telegram api:**
`{
  "update_id": 33826834,
  "edited_message": {
    "message_id": 1713,
    "from": {
      "id": 743826780,
      "is_bot": false,
      "first_name": "Vahid",
      "last_name": "Khorasani",
      "username": "v8hid",
      "language_code": "en"
    },
    "chat": {
      "id": 743826780,
      "first_name": "Vahid",
      "last_name": "Khorasani",
      "username": "v8hid",
      "type": "private"
    },
    "date": 1661125877,
    "edit_date": 1661133451,
    "dice": {
      "emoji": "🏀",
      "value": 2
    }
  }
}`

### To Reproduce

You can send this json string and sending a request to a Route that calls run() on Nutgram instance and get the same error.

### Expected behavior

I'm not sure what is the expected behavior but pretty sure this is the result of using this command:
`
$this->nutgram->sendDice();
`

**Comment by Lukasss93** [comment]
I was unable to replicate the problem.

This is not a Nutgram bug, a working example below:
![immagine](https://user-images.githubusercontent.com/4071613/187991467-d02c832c-9260-4a2a-8afd-5b4085c0e195.png)
