### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pouriaho** [nutgram/nutgram#244]
### Nutgram version

^3.8

### Describe the bug

This method `onApiError` is not working this way (with a pattern):

```php
$bot->onApiError('chat not found', function (Nutgram $bot, TelegramException $ex) {
    $bot->sendMessage('chat not found!');
});
```

Can you please test it?

And another issue is that when the `onApiError` method was called, the code execution continued. For example, when in a conversation. Is this normal?

Thank you

### To Reproduce

...

### Expected behavior

...

**Comment by Lukasss93** [comment]
pattern must be the exact text, try to add .* before and after your text
```
// before
'chat not found'

// after
'.*chat not found.*'
```

how to stop code execution:
```php
// custom exception
class ChatNotFoundException extends Exception{}

// routes
$bot->onApiError('.*chat not found.*', fn (Nutgram $bot, $e) {
    throw new ChatNotFoundException($e->getMessage());
});
```
