### ISSUE TITLE
[BUG] getUpdates uses POST, but 'offset' must be GET param

### ISSUE THREAD

**Issue by shanginn** [nutgram/nutgram#250]
### Nutgram version

3.8.0

### Describe the bug

To mark update as read we need to send `offset` GET param to Telegram getUpdates endpoint.

But method \SergiX44\Nutgram\Telegram\Client@getUpdates uses `requestJson` and it always uses POST.

I don't know if it works as expected with `$bot->run()`, but i'm trying to handle my updates with 
`$bot->getUpdates(['offset' => $highestId + 1])` and it doesn't mark any updates as read

### To Reproduce

```php
$bot = new Nutgram(config('nutgram.token'));

// Send message to the Telegram bot

$updates = $bot->getUpdates();

foreach ($updates as $update) {
    $highestId = $update->update_id;
}

// This should mark all the updates as read
$bot->getUpdates(['offset' => $highestId + 1]);

// But all the updates is still there
$updates = $bot->getUpdates();

assert(count($updates) !== 0); // true
```

### Expected behavior

Updates mark as processed when getUpdates called with offset higher than last update id

**Comment by Lukasss93** [comment]
Try this:
![immagine](https://user-images.githubusercontent.com/4071613/201738335-a6c2c9b0-8557-42bb-9a7d-385d11b805ff.png)

But,
I suggest you to use our
