### ISSUE TITLE
[BUG] Class "Symfony\Component\HttpFoundation\Response" not found 

### ISSUE THREAD

**Issue by its2easy** [nutgram/nutgram#251]
### Nutgram version

3.7.8, 3.8.0

### Describe the bug

When I download a file from user
```
$bot->onMessageType(MessageTypes::DOCUMENT, function (Nutgram $bot) {
    $document = $bot->message()->document;
    $file = $bot->getFile($document->file_id);
    $bot->downloadFile($file, BASE_PATH . FILES_FOLDER . "/" . $document->file_name);
}
```
the file is downloaded and saved in the folder, but in `$bot->onException` I get an error:
```
Error: Class "Symfony\Component\HttpFoundation\Response" not found in D:\projects\report-bot\vendor\nutgram\nutgram\src\Telegram\Client.php:186
Stack trace:
#0 D:\projects\report-bot\receive.php(67): SergiX44\Nutgram\Nutgram->downloadFile()
#1 [internal function]: {closure}() 
#2 D:\projects\report-bot\vendor\nutgram\nutgram\src\Handlers\Handler.php(96): call_user_func()
#3 [internal function]: SergiX44\Nutgram\Handlers\Handler->__invoke()
#4 D:\projects\report-bot\vendor\nutgram\nutgram\src\Middleware\Link.php(41): call_user_func()
#5 D:\projects\report-bot\vendor\nutgram\nutgram\src\Nutgram.php(260): SergiX44\Nutgram\Middleware\Link->__invoke()
#6 D:\projects\report-bot\vendor\nutgram\nutgram\src\Nutgram.php(248): SergiX44\Nutgram\Nutgram->fireHandlers()
#7 D:\projects\report-bot\vendor\nutgram\nutgram\src\RunningMode\Webhook.php(68): SergiX44\Nutgram\Nutgram->processUpdate()
#8 D:\projects\report-bot\vendor\nutgram\nutgram\src\Nutgram.php(220): SergiX44\Nutgram\RunningMode\Webhook->processUpdates()
#9 D:\projects\report-bot\receive.php(91): SergiX44\Nutgram\Nutgram->run() 
#10 {main}
```

### To Reproduce

1. Send a document to the bot
2. Save the document on the server
3. Catch errors

### Expected behavior

downloadFile() works without errors

**Comment by Lukasss93** [comment]
I was unable to replicate the problem.

Try to run composer dump-autoload -o and try again

**Comment by its2easy** [comment]
dump-autoload and reinstall have no effect. I cloned nutgram/nutgram and `composer install` inside, and in this case `symfony/http-foundation` folder exists in `vendor`. Maybe this package is required only by some require-dev dependency and not installed when nutgram is used as dependency itself? 
I don't use php often and can't properly debug this but it seems like symfony/http-foundation -> laravel/framework -> spatie/laravel-ray -> orchestra/testbench (dev)
And your tests are working becase they run in dev environment

**Comment by its2easy** [comment]
Also when I use nutgram in my project `illuminate/macroable` is installed in separate folder `vendor/illuminate/macroable`, but in cloned nutgram/nutgram it is in `vendor/laravel/framework/src/illuminate/macroable`
