### ISSUE TITLE
[BUG] Missing edited_message inside Update::getChat method

### ISSUE THREAD

**Issue by Lukasss93** [nutgram/nutgram#277]
### Nutgram version

<= 3.9

### Describe the bug

Missing edited_message inside Update::getChat method

### To Reproduce

https://github.com/nutgram/nutgram/blob/master/src/Telegram/Types/Common/Update.php#L197

### Expected behavior

Add 
```php 
$this->edited_message !== null => $this->edited_message->chat
``` 
inside `match`

**Comment by poorbash** [comment]
also in ```setChat``` method...
