### ISSUE TITLE
Send message to saved chat id not working

### ISSUE THREAD

**Issue by themindfactory** [nutgram/nutgram#344]
### Nutgram version

Current 

### Describe the bug

When I subsantiate the class I then immediately send a message to a chat ID that I have made note of from a prior chat and the message does not show up in the thread on the telegram app

### To Reproduce

use SergiX44\Nutgram\Nutgram;

$bot = new Nutgram($_ENV['TOKEN']);

$chatid = 123456;
    $bot->sendMessage('Ciao!', ['chat_id'=>$chatid]);

### Expected behavior

Sends message to chat

**Comment by Lukasss93** [comment]
Please give us more context.
- What is the error you are receiving?
- Send a screenshot of your code and the error

**Comment by themindfactory** [comment]
So I ran the code below and when I send command /start I can see the chat id, then I inserted that number into $bot->sendMessage('i am back', ['chat_id'=>6116504604]); and re-run the code and expect the 'i am back' message to appear once the code is re-run.

 ```
require '../vendor/autoload.php';
use SergiX44\Nutgram\Nutgram;

$bot = new Nutgram("");

$bot->onCommand('start', function(Nutgram $bot) {
    $bot->sendMessage('Ciao!');
    echo($bot->chatId());
});

$bot->run();
$bot->sendMessage('i am back', ['chat_id'=>6116504604]);
```

**Comment by themindfactory** [comment]
The idea was I would log to a database the chat_id and at anytime I could resend message back to the user.

**Comment by Lukasss93** [comment]
If you are using the polling mode, the run method will be listening forever and you will not be able to do anything after it. You will have to use a parallel script or find another way.

**Comment by themindfactory** [comment]
OK so I tried this:

<?php

```
require '../vendor/autoload.php';
use SergiX44\Nutgram\Nutgram;
$bot = new Nutgram("6039782080:AAHQdKr5dqQTO2TvXh0X_HyPc-Uly2K_FKY");
$bot->setRunningMode(Webhook::class);
$bot->sendMessage('Nice pic!', ['chat_id' => 6116504604]);
$bot->run();

```
and it works to send the message and then I expect ->run() to run once and the script to exit....
but it thinks at the end that $bot is a string, not sure how $bot got assigned a string :-)

```
PHP Fatal error:  Uncaught Error: Call to a member function processUpdates() on string in /var/www/vhosts/onlysend.me/public_html/vendor/nutgram/nutgram/src/Nutgram.php:228
Stack trace:
#0 /var/www/vhosts/onlysend.me/public_html/tapptest/demo1.php(8): SergiX44\Nutgram\Nutgram->run()
#1 {main}
  thrown in /var/www/vhosts/onlysend.me/public_html/vendor/nutgram/nutgram/src/Nutgram.php on line 228
```

**Comment by Lukasss93** [comment]
See this:
https://github.com/nutgram/nutgram/discussions/334
