### ISSUE TITLE
[FEATURE] skip global middleware for group routes

### ISSUE THREAD

**Issue by kriptogenic** [nutgram/nutgram#392]
### Is your feature request related to a problem? Please describe.

I love new group method, can you also add skiping global middlewares for groups?

### Describe the solution you'd like

Now I have
```
$bot->group(new CheckAdminChatMiddleware(config('bot.chats.withdraw')), function (Nutgram $bot) {
    $bot->onCommand('success, [OperationHandler::class, 'success'])
        ->skipGlobalMiddlewares([SpecifyClientMiddleware::class]);
    $bot->onCommand('cancel', [OperationHandler::class, 'cancel'])
        ->skipGlobalMiddlewares([SpecifyClientMiddleware::class]);
});
```

I want
```
$bot->group(new CheckAdminChatMiddleware(config('bot.chats.withdraw')), function (Nutgram $bot) {
    $bot->onCommand('success, [OperationHandler::class, 'success']);
    $bot->onCommand('cancel', [OperationHandler::class, 'cancel']);
})->skipGlobalMiddlewares([SpecifyClientMiddleware::class]);
```

**Comment by SergiX44** [comment]
Sorry but if you need to skip a global middleware, it means that middleware should not be a global one.
Create a group with that middleware, and keep the other handlers you want to skip outside.

**Comment by kriptogenic** [comment]
Group middleware has one bug, when I use group midlleware with conversations, middleware not works in steps

**Comment by kriptogenic** [comment]
Later I will show code with that bug

**Comment by Lukasss93** [comment]
open a new issue
