### ISSUE TITLE
[BUG] `Conversation` PHPStan static analysis fail

### ISSUE THREAD

**Issue by Z3d0X** [nutgram/nutgram#398]
### Nutgram version

3.17.0

### Describe the bug

PHPStan static analysis on `start` Method in `SergiX44\Nutgram\Conversations\Conversation`
```php
 /**
 * @param  Nutgram  $bot
 *
 * @return never
 */
public function start(Nutgram $bot)
{
    throw new RuntimeException('Attempt to start an empty conversation.');
}
```
Because of the `@return never` doc block  static analysis of PHPStan fails

```
Method App\Telegram\Conversations\MyConversation::start() should always throw an exception or
terminate script execution but doesn't do that.
```

### Expected behavior

PHPStan static analysis to work on `SergiX44\Nutgram\Conversations\Conversation` `start` method, out of the box

### Screenshots

<img width="859" alt="image" src="https://user-images.githubusercontent.com/75579178/225104935-db989fd9-5764-4c5d-8994-eabcaafac168.png">

### Additional context

I know I can fix this by using a PHPStan stub to override the return type in userland (my code).

Feel free to close this if you don't think this is an issue and should addressed

**Comment by SergiX44** [comment]
Please can you move you version to `dev-master` and try again?

**Comment by Z3d0X** [comment]
Yes dropping the phpdoc, fixes this for me
