### ISSUE TITLE
[BUG] Each page update triggers a connection to the TG server

### ISSUE THREAD

**Issue by ExecPHP** [nutgram/nutgram#402]
### Nutgram version

3.17.1

### Describe the bug

I use laravel + nutgram, there is also a back office for employees, I noticed that the more intensive requests are received in routing, the more often an error in the bot begins to appear:

$bot->onApiError ->  {"msg":"Too Many Requests: retry after 2041","code":429,"file":"/var/www/bot-helper.net/vendor/nutgram/nutgram/src/Telegram/Client.php","line":340}

### To Reproduce

'routes' => true,
'mixins' => true,

It's enough to simply update any page about 20 times in a row and this error will begin to pour in

### Expected behavior

Every update of the laravel page should not connect to telegram servers

### Additional context

I suspect it has to do with the Nut g ram Service Provider and its code:
```
if ($app->runningInConsole()) {
                $bot->setRunningMode(Polling::class);
            } else {
                $webhook = Webhook::class;
                if (config('nutgram.safe_mode', false)) {
                    // take into account the trust proxy Laravel configuration
                    $webhook = new Webhook(fn () => $app->make('request')?->ip());
                }

                $bot->setRunningMode($webhook);
            }
```

**Comment by Lukasss93** [comment]
Please give us more context. 
Where did you place the `$bot->run();` ?

**Comment by ExecPHP** [comment]
I figured out what the problem was, it was related to the fact that I was in routes/telegram.php added $bot->registerMyCommands(); it called every upload request to the tg api
