### ISSUE TITLE
[BUG] User id detection mistake 

### ISSUE THREAD

**Issue by KakoitoTatar** [nutgram/nutgram#404]
### Nutgram version

3.17.1

### Describe the bug

Either i don't understand something or Nutgram detects userId wrong.
In Nutgram::stepConversation userId equal to botId, but when you get currentConversation in ResolveHandlers::currentConversation it detects as valid userId

### To Reproduce

1. Create simple two step conversation
2. Begin it
3. In ConversationCache dump userId it will be equal to your botId
4. Dump same userId while Nutgram trying to restore Conversation it will be equal to userId

### Expected behavior

UserId equal to UserId
![image](https://user-images.githubusercontent.com/24491062/225995260-aee497c8-9216-4c64-8589-612a7e6cbeb5.png)

### Screenshots

![image](https://user-images.githubusercontent.com/24491062/225995580-706be14e-0602-49c4-a2d2-a249b421f6e8.png)

**Comment by KakoitoTatar** [comment]
Basically after sending a message userId of client getting replaced with userId of author of last sended message (your bot)

**Comment by KakoitoTatar** [comment]
Ok, for now i'll just use explicit call to stepConversation it seems like it fixes all my problems

**Comment by SergiX44** [comment]
Can you please post a snippet to reproduce the issue?

**Comment by KakoitoTatar** [comment]
`<?php

declare(strict_types=1);

namespace App\Application\Actions;

use SergiX44\Nutgram\Conversations\Conversation;
use SergiX44\Nutgram\Nutgram;
use SergiX44\Nutgram\Telegram\Types\Keyboard\KeyboardButton;
use SergiX44\Nutgram\Telegram\Types\Keyboard\ReplyKeyboardMarkup;

class TestConversation extends Conversation
{
    /**
     * @param Nutgram $bot
     * @return never|void
     * @throws \Psr\SimpleCache\InvalidArgumentException
     */
    public function start(Nutgram $bot)
    {
        $bot->sendMessage('To step two', [
            'reply_markup' => ReplyKeyboardMarkup::make(resize_keyboard: true, selective: true)
                ->addRow(KeyboardButton::make('Let\'s go'))
        ]);
        $this->next('stepTwo');
    }

    /**
     * @param Nutgram $bot
     * @return void
     */
    public function stepTwo(Nutgram $bot)
    {
        $bot->sendMessage('start', [
            'reply_markup' => ReplyKeyboardMarkup::make(resize_keyboard: true, selective: true)
                ->addRow(KeyboardButton::make('Let\'s go'))
        ]);
    }
}`

**Comment by KakoitoTatar** [comment]
```
<?php

declare(strict_types=1);

namespace App\Application\Actions;

use SergiX44\Nutgram\Conversations\Conversation;
use SergiX44\Nutgram\Nutgram;
use SergiX44\Nutgram\Telegram\Types\Keyboard\KeyboardButton;
use SergiX44\Nutgram\Telegram\Types\Keyboard\ReplyKeyboardMarkup;

class TestConversation extends Conversation
{
    /**
     * @param Nutgram $bot
     * @return never|void
     * @throws \Psr\SimpleCache\InvalidArgumentException
     */
    public function start(Nutgram $bot)
    {
        $bot->sendMessage('To step two', [
            'reply_markup' => ReplyKeyboardMarkup::make(resize_keyboard: true, selective: true)
                ->addRow(KeyboardButton::make('Let\'s go'))
        ]);
        $this->next('stepTwo');
    }

    /**
     * @param Nutgram $bot
     * @return void
     */
    public function stepTwo(Nutgram $bot)
    {
        $bot->sendMessage('start', [
            'reply_markup' => ReplyKeyboardMarkup::make(resize_keyboard: true, selective: true)
                ->addRow(KeyboardButton::make('Let\'s go'))
        ]);
    }
}
```
Basically it's supposed to throw you from first to second step and than back, but because after sendMessage userId becomes equal to id of your bot your cache_keys becomes invalid and conversation stops

**Comment by Preshy** [comment]
Facinf a similar issue where the callback is not persistent on the request so somehow it forgets to carry data from the user response.

**Comment by Lukasss93** [comment]
https://user-images.githubusercontent.com/4071613/230741462-252321ae-43ef-49fb-a7ee-56cfa0645255.mp4

Are you sure?
