### ISSUE TITLE
[BUG] onMessage not working on Laravel

### ISSUE THREAD

**Issue by fauzipadlaw** [nutgram/nutgram#409]
### Nutgram version

3.17.1

### Describe the bug

I am using Nutgram on Laravel 9 with webhook. onMessage method is not working while onText is working fine.

### To Reproduce

1. Add this route in telegram.php
```
$bot->onMessage(function(Nutgram $bot) {
    $bot->sendMessage('TEST');
});

$bot->onText('something',function(Nutgram $bot) {
    $bot->sendMessage('TEST SOMETHING');
});
```

2. Test the code, the output is like this
<img width="610" alt="Screenshot 2023-03-25 at 6 38 24 AM" src="https://user-images.githubusercontent.com/15975922/227663036-569e476f-61b7-495a-89f1-a6dee7a71426.png">

### Expected behavior

onMessage method is working without issues.

### Additional context

PHP 8.0.27

**Comment by Lukasss93** [comment]
I just remembered that it's a feature: specific handlers block generic handlers. This behavior is not yet specified in the documentation.
