### ISSUE TITLE
Call step in another conversation

### ISSUE THREAD

**Issue by IkromKhakimov** [nutgram/nutgram#416]
```
class FindDrugConversation extends Conversation
{
    public function start(Nutgram $bot)
    {
        // if location not choosed
        (new ChooseLocationConversation)->start($bot);
        return;
 }
```

// This not work

**Comment by Lukasss93** [comment]
Why call a conversation inside a conversation? It doesn't make any sense.
Just use 1 conversation to do your checks...

https://nutgram.dev/docs/usage/conversations#begin-a-conversation

**Comment by IkromKhakimov** [comment]
Agree, but i wanted use SOLID principe, FindDrugsConversation, ChooseLocationConversation, both of them have multiple steps. User type "Find drugs", and he should go to ChooseLocationConversation first, if he not selected location before

**Comment by Lukasss93** [comment]
Try this (not tested):

```php
class FindDrugConversation extends Conversation
{
    public function start(Nutgram $bot)
    {
        // your code
        $this->end();
        ChooseLocationConversation::begin($bot);
        return;
 }
```
