### ISSUE TITLE
[FEATURE] Add DYNAMIC bot token change

### ISSUE THREAD

**Issue by spokeswamp** [nutgram/nutgram#475]
### Is your feature request related to a problem? Please describe.

I want channel administrators to create their own bots and then invite them into their own channels/groups, as the bots work with user generated content that they upload, then the bot sends this to channel/group chats.

This could be anything, such as a picture of inappropriate content and as a bot developer I don't want to be responsible for this content or get the main bot blocked, the token owner should be responsible for this.

### Describe the solution you'd like

Add method $bot->setToken(<TOKEN>), so that in route "/bot/{token}" (route processing WebHook) I can change bot's token to the one that came and later work with it.

### Describe alternatives you've considered

Changing values in the .env on the fly, which did not help

### Additional context

I know there is a "multibot-support" branch at the moment, but it does not implement the functionality at all

**Comment by SergiX44** [comment]
The Nutgram instances are immutable by design, so it means that you can't change the input configuration after creating an instance, for many different reasons.

If you need to interact with Telegram with different tokens, you have to instantiate an instance for each token.
