### ISSUE TITLE
[BUG] [04-Jun-2023 17:16:15 UTC] PHP Fatal error:  Uncaught JsonException: Syntax error in/vendor/nutgram/nutgram/src/RunningMode/Webhook.php:59 Stack trace: #0 /vendor/nutgram/nutgram/src/RunningMode/Webhook.php(59): json_decode() #1 /vendor/nutgram/nutgram/src/Nutgram.php(229): SergiX44\Nutgram\RunningMode\Webhook->processUpdates() #2 /vendor/nutgram/nutgram/src/RunningMode/Webhook.php on line 59

### ISSUE THREAD

**Issue by festars** [nutgram/nutgram#479]
### Nutgram version

4.0

### PHP version

8.2

### Framework

No Framework

### Cache driver

Arraycache

### Describe the bug

Cant run on webhook

### Expected behavior

work

### Additional context

[04-Jun-2023 17:16:15 UTC] PHP Fatal error:  Uncaught JsonException: Syntax error in /vendor/nutgram/nutgram/src/RunningMode/Webhook.php:59
Stack trace:
#0 vendor/nutgram/nutgram/src/RunningMode/Webhook.php(59): json_decode()
#1 botpa/vendor/nutgram/nutgram/src/Nutgram.php(229): SergiX44\Nutgram\RunningMode\Webhook->processUpdates()
#2 /home/helaspot/abepay.helaspot.com/botpa/index.php(57): SergiX44\Nutgram\Nutgram->run()
#3 {main}
  thrown in /vendor/nutgram/nutgram/src/RunningMode/Webhook.php on line 59

**Comment by Lukasss93** [comment]
https://github.com/nutgram/nutgram/discussions/352

**Comment by festars** [comment]
above is my code, webhook is set correctly @Lukasss93

**Comment by somel-web** [comment]
in case: just check php8.2-curl extension is installed.
I had the same bug, migrating to a brand new server, my old code stopped working:  
telegram server responded with a 505 HTTP Version Not Supported.
(Uncaught GuzzleHttp\Exception\ServerException).
With php-curl extension correctly installed, now it's ok
