### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by rykon97** [nutgram/nutgram#491]
### Nutgram version

4.0.1

### PHP version

8.2

### Framework

Laravel

### Cache driver

Laravel

### Describe the bug

I have this error when run in production mode with webhook in Laravel website:

`[2023-06-10 06:14:29] production.ERROR: Object of class SergiX44\Nutgram\Telegram\Properties\UpdateType could not be converted to string {"exception":"[object] (Error(code: 0): Object of class SergiX44\\Nutgram\\Telegram\\Properties\\UpdateType could not be converted to string at /home/forge/bot.rykon.io/vendor/nutgram/nutgram/src/RunningMode/Webhook.php:65)
[stacktrace]
#0 /home/forge/bot.rykon.io/vendor/nutgram/nutgram/src/RunningMode/Webhook.php(65): sprintf()
#1 /home/forge/bot.rykon.io/vendor/nutgram/nutgram/src/Nutgram.php(205): SergiX44\\Nutgram\\RunningMode\\Webhook->processUpdates()
#2 /home/forge/bot.rykon.io/app/Http/Controllers/FrontController.php(14): SergiX44\\Nutgram\\Nutgram->run()
#3 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\FrontController->__invoke()
#4 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#5 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#6 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#7 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#8 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#9 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#11 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(152): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(118): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequest()
#13 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php(80): Illuminate\\Routing\\Middleware\\ThrottleRequests->handleRequestUsingNamedLimiter()
#14 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\ThrottleRequests->handle()
#15 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#17 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#18 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#19 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#20 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#21 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#22 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#24 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#25 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#27 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#28 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#30 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#32 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#33 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#34 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#36 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#38 /home/forge/bot.rykon.io/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#39 /home/forge/bot.rykon.io/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#40 {main}
"} 
`

How can I fix it?

### To Reproduce

1. Make Laravel project with last version Laravel + Nutgram, and make controller of webhook as explained in docs of Nutgram

### Expected behavior

I expect in function nutgram/nutgram/src/RunningMode/Webhook.php:65 

`$bot->getContainer()
            ->get(LoggerInterface::class)
            ->debug(sprintf('Received update: %s%s%s', $update->getType(), PHP_EOL, $input));`

sprintf can't convert object to string

**Comment by Lukasss93** [comment]
This bug is already fixed in Nutgram https://github.com/nutgram/nutgram/releases/tag/4.0.1

Are you sure about your Nutgram version?

**Comment by SergiX44** [comment]
Yes, you probably have installed the 4.0.0, here the error line on the old version.
https://github.com/nutgram/nutgram/pull/480/files#diff-7d6420eb18a494896cbe7baef24d313381c784091696cb6a31e2e9553e0ba278L65

Please run a composer update, feel free to reopen if needed.
