### ISSUE TITLE
[BUG] Conversation step don't working (after update?)

### ISSUE THREAD

**Issue by Kartulin** [nutgram/nutgram#506]
### Nutgram version

"nutgram/symfony-bundle": "1.0.1"

### PHP version

8.2.7

### Framework

Symfony 6.3.1

### Cache driver

default Nutgram

### Describe the bug

Steps in conversations stopped working. Doesn't move to the next step.

### To Reproduce

Just create any conversation with two steps. The first step works. The second step doesn't work.

### Expected behavior

Should go to the right steps of the conversation

### Screenshots

![Снимок экрана от 2023-06-27 14-50-41](https://github.com/nutgram/nutgram/assets/19319937/2ad8f30c-19d7-4912-9a11-1aa598a74e10)

and after sending the response - I see an error in the logs
![image](https://github.com/nutgram/nutgram/assets/19319937/33a38ad3-257b-4ed5-af72-f6ad8f9a0211)
Strange, but just a couple of days ago - everything worked.

### Additional context

Telegram.php
```php
Conversation::refreshOnDeserialize();

//$bot->middleware(AuthMiddleware::class);
/** После добавления новых команд - не забыть nutgram:register-commands!!
 */
$bot->onCommand('start', StartCommand::class);
$bot->onCommand('news', NewsCommand::class)->description('Последние новости');
`
nutgram.yaml - is default
cache.yaml - is default from Symfony

**Comment by Kartulin** [comment]
![image](https://github.com/nutgram/nutgram/assets/19319937/2ad3c730-38e4-45a3-bbcc-3c27a1dd60a5)
Hmm.. the problem is with
 use TwigTrait;
If you remove it - everything works correctly ...
It remains to figure out "how to make a normal decorator for Twig, so that you can conveniently render templates"...

**Comment by Kartulin** [comment]
![image](https://github.com/nutgram/nutgram/assets/19319937/a01f6b6f-8329-40be-bb43-d4b04aba36f3)
Нашел замену для трейта... был трейт - стал сервис =)
Извините за беспокойство, парни.
У вас - чудесная библиотека... Я бы даже сказал, что Nutgram - это full-telegram-framework!
Тикет можно закрывать...

**Comment by SergiX44** [comment]
Thats pretty strange tbh, will probably investigate the trait behaviour in the future
