### ISSUE TITLE
[BUG] Undefined constant "SergiX44\Nutgram\RunningMode\STDERR"

### ISSUE THREAD

**Issue by camoralb** [nutgram/nutgram#542]
### Nutgram version

4.4

### PHP version

8.2

### Framework

No Framework

### Cache driver

ArrayCache

### Describe the bug

I install it via composer with PHP 8.2

Fatal error: Uncaught Error: Undefined constant "SergiX44\Nutgram\RunningMode\STDERR" in /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Container.php:151 Stack trace: #0 /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Container.php(151): ReflectionClass->newInstance() https://github.com/nutgram/nutgram/pull/1 /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Container.php(51): SergiX44\Container\Container->resolve('SergiX44\Nutgra...') https://github.com/nutgram/nutgram/pull/2 /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Definition.php(48): SergiX44\Container\Container->get('SergiX44\Nutgra...') https://github.com/nutgram/nutgram/pull/3 /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Container.php(43): SergiX44\Container\Definition->make(Object(SergiX44\Container\Container)) https://github.com/nutgram/nutgram/pull/4 /Users/carlosmorales/Downloads/bot/vendor/nutgram/nutgram/src/Nutgram.php(200): SergiX44\Container\Container->get('SergiX44\Nutgra...') https://github.com/nutgram/nutgram/pull/5 /Users/carlosmorales/Downloads/bot/test.php(25): SergiX44\Nutgram\Nutgram->run() https://github.com/nutgram/nutgram/pull/6 {main} Next SergiX44\Container\Exception\NotFoundException: Cannot resolve 'SergiX44\Nutgram\RunningMode\Polling' in /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Exception/NotFoundException.php:13 Stack trace: #0 /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Container.php(53): SergiX44\Container\Exception\NotFoundException::notResolvable('SergiX44\Nutgra...', Object(Error)) https://github.com/nutgram/nutgram/pull/1 /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Definition.php(48): SergiX44\Container\Container->get('SergiX44\Nutgra...') https://github.com/nutgram/nutgram/pull/2 /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Container.php(43): SergiX44\Container\Definition->make(Object(SergiX44\Container\Container)) https://github.com/nutgram/nutgram/pull/3 /Users/carlosmorales/Downloads/bot/vendor/nutgram/nutgram/src/Nutgram.php(200): SergiX44\Container\Container->get('SergiX44\Nutgra...') https://github.com/nutgram/nutgram/pull/4 /Users/carlosmorales/Downloads/bot/test.php(25): SergiX44\Nutgram\Nutgram->run() https://github.com/nutgram/nutgram/pull/5 {main} thrown in /Users/carlosmorales/Downloads/bot/vendor/sergix44/container/src/Exception/NotFoundException.php on line 13

### To Reproduce

I am installing nutgram with "composer require nutgram/nutgram", adding this code in a file in same directory than composer.json. Then register it in my bot, and sending commands to the chat. The error below is got from the system log (apache log)

<?php
ini_set("display_error", "On");

$token = 'BOT_TOKEN_HERE';

use SergiX44\Nutgram\Nutgram;

require 'vendor/autoload.php';

$bot = new Nutgram($token);

$bot->onCommand('start', function(Nutgram $bot) {
    $bot->sendMessage('Ciao!');
});

$bot->onText('My name is {name}', function(Nutgram $bot, string $name) {
    $bot->sendMessage("Hi $name");
});

$bot->run();

### Expected behavior

It would have to add the library and execute the program without  any "500 Fatal error".

**Comment by SergiX44** [comment]
You are trying to use the Polling mode in a web context (apache_mod, fcgi, fpm or whatever). The polling running mode can be only used in a console environment (since it will be a long running process).
Please read the documentation about getting updates https://nutgram.dev/docs/usage/getting_updates
