### ISSUE TITLE
[FEATURE] Add support for igbinary serializer

### ISSUE THREAD

**Issue by asanikovich** [nutgram/nutgram#571]
### Describe the solution you'd like

**Igbinary** is a drop in replacement for the standard php serializer. Instead of the time and space consuming textual representation used by PHP's serialize, igbinary stores php data structures in a compact binary form. Memory savings are significant when using memcached, APCu, or similar memory based storages for serialized data. The typical reduction in storage requirements are around 50%. The exact percentage depends on your data.

### Additional context

Currently, it doesn't work. It fails for example on:
`InlineMenu::$buttons must not be accessed before initialization`

**Comment by sergix44** [comment]
Is not that drop in if it doesnt behave like the builtin serializer.
Does provide any additional benefit? Storage space I dont think is much of a concern, Nutgram uses serialized classes to store statuses for conversations, which is usually lasts couple of minutes, max the conversation TTL if abandoned and never terminated by a user.

**Comment by Lukasss93** [comment]
Feel free to send a PR for that 👍
