### ISSUE TITLE
[FEATURE] running multiple bots with one source code

### ISSUE THREAD

**Issue by flakka2022** [nutgram/nutgram#582]
### Is your feature request related to a problem? Please describe.

i want to run multiple bots using one nutgram/laravel project but it requires setting only one token in env as TELEGRAM_TOKEN . the way i want use is to pass a id for each but in route then grab bot information from database instead of just have one token defined . how i can do this ?

### Describe the solution you'd like

provide a way to run multiple similar bots using one source code

**Comment by sergix44** [comment]
Duplicated of #487

**Comment by mahmoodmohaghegh** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> i want to run multiple bots using one nutgram/laravel project but it requires setting only one token in env as TELEGRAM_TOKEN . the way i want use is to pass a id for each but in route then grab bot information from database instead of just have one token defined . how i can do this ?
> 
> ### Describe the solution you'd like
> 
> provide a way to run multiple similar bots using one source code
> 
> ### Describe alternatives you've considered
> 
> _No response_
> 
> ### Additional context
> 
> _No response_
