### ISSUE TITLE
[FEATURE] Add helpers for the replied messages

### ISSUE THREAD

**Issue by devdasher** [nutgram/nutgram#594]
### Is your feature request related to a problem? Please describe.

My Code:

![photo_2023-10-05_17-38-12](https://github.com/nutgram/nutgram/assets/78247242/ecc4b607-e677-4588-91d7-65c461c225a4)

Natgram has [helpers ](https://nutgram.dev/docs/usage/handlers#available-helpers) for users and current user messages. But it seems that there is no helper for the messages that are replied to.

For example, suppose in a group user A replies to user B's message, there is no helper to get the details of user B's message.

Suppose I want to get the `user_id` or `chat_id` of user B's message easily (like this: `$bot->userId()` or `$bot->chatId()`). But this is not possible.

It would be good if helpers for replied messages were added.

This is sometimes confusing and causes small bugs in the program. Because not all developers are professionals and are not familiar with the Telegram API. For example, if our code is as follows:
```php
// Suppose the input update sent from an group:
$userId = $bot->message()->reply_to_message->chat->id;

// Above code return the group's chat_id and not the user's chat_id and finally it sometimes causes small bugs like this...

```

### Describe the solution you'd like

I can't think of a solution, but if it can be done like this, it might be good:

![photo_2023-10-05_17-47-28](https://github.com/nutgram/nutgram/assets/78247242/3a0214ce-e83e-49c7-be81-4e0a801792f4)

### Additional context

These additional helpers can be added as well:
```php
$bot->repliedMessage()->user();
$bot->repliedMessage()->chat();
//....


```

**Comment by Lukasss93** [comment]
We will not add a `repliedMessage` helper for now.

Just do this:
```php
$user_id = $bot->message()?->reply_to_message?->chat->id ?? $bot->userId();
```
