### ISSUE TITLE
[BUG] Curl failure

### ISSUE THREAD

**Issue by etdte** [nutgram/nutgram#602]
### Nutgram version

4.10.0

### PHP version

8.2

### Framework

Laravel

### Cache driver

Redis

### Describe the bug

Every command interacting with Telegram API including provided `artisan nutgram:run` command, results in error `cURL error 0: The cURL request was retried 3 times and did not succeed`

### To Reproduce

1. Create fresh Laravel project
2. Install Nutgram, set up telegram token
3. Run `php artisan nutgram:run` command

### Expected behavior

Expecting command not to fail

### Screenshots

<img width="1116" alt="Screenshot 2023-10-25 at 10 54 10" src="https://github.com/nutgram/nutgram/assets/7522610/83400b02-6ed5-4448-b42b-ba08544129e2">

### Additional context

Guzzle version is 7.8.0

**Comment by Lukasss93** [comment]
I wasn't able to reproduce. Please provide more information about this problem.

**Comment by etdte** [comment]
Okay, here is short video regarding problem I'm talking about. Can understand why you can't replicate, what information should I check, exactly? Does example on screenshot aren't clear enough? What I did wrong, as it seems like not much can go wrong on the package user side? 

https://youtu.be/YT3YUXqZEI4

**Comment by sergix44** [comment]
I'm sorry, but from the video and the screenshots its pretty clear that the issue is the underlying curl, probably related to your local setup/network/something, so out of Nutgram's control.
The only thing that comes to my mind is forcing Guzzle to use the stream handler instead of curl, by putting inside the config:

```php
    // Extra or specific configurations
    'config' => ['client' => ['handler' => new StreamHandler()]],
```
To see that something changes, and verifying that a curl to the url you got in the error message (api.telegram.org/bot...) is actually reachable and you get a valid json response from that.

**Comment by etdte** [comment]
I've tried your suggestion, seems like problem is in on Nugram side
<img width="1256" alt="Screenshot 2023-10-27 at 15 09 25" src="https://github.com/nutgram/nutgram/assets/7522610/5d0b7628-9ee6-43be-9faf-61cdc79ba810">

from what I see, constants used in `mapResponse` method are unreachable by the code, because are defined inside `/src/Handlers/CollectHandlers.php`, but `Client` class aren't extending from it. 

<img width="854" alt="Screenshot 2023-10-27 at 15 10 17" src="https://github.com/nutgram/nutgram/assets/7522610/6f1998ea-9816-4177-9137-e4db153b395b">

**Comment by sergix44** [comment]
At this point I dont think you are running that on php8.2 or you have a broken php installation. If there was really that problem all the unit tests and bots in production that use Nutgram would all be broken (and they are not).

**Comment by etdte** [comment]
@sergix44 please, take a closer look at JSON which was provided in original issue. I am getting JSON from telegram, everything is reachable, and responses are healthy.
<img width="813" alt="Screenshot 2023-10-27 at 15 45 01" src="https://github.com/nutgram/nutgram/assets/7522610/b274715b-7c3a-4484-b0ff-54f0ac34422e">

**Comment by DanielSpravtsev** [comment]
> @sergix44 please, take a closer look at JSON which was provided in original issue. I am getting JSON from telegram, everything is reachable, and responses are healthy.
> 
> <img width="813" alt="Screenshot 2023-10-27 at 15 45 01" src="https://github.com/nutgram/nutgram/assets/7522610/b274715b-7c3a-4484-b0ff-54f0ac34422e">
> 
> 
> 
> 
> 
> it is literally next line after "Listening..."
> 
> 
> 
> Same with the video - there is log of responses from api.telegram.org, and they all healthy, and non-failing, i.e. no authorisation errors or not founds, whatever. 
> 
> 
> 
> Regarding php version - video literally begins with dump of current version. So, it is not the case.


Is it a telegram response? 
Nutgram wrap any TG response and output it in json format, so it can be just empty nutgram skeleton response

**Comment by ChiefC0de** [comment]
Have the same issue

**Comment by Lukasss93** [comment]
Please provide more context: hardware, software, etc...

This is my installation guide on Ubuntu:
https://www.youtube.com/watch?v=n-mAed7mVtI

**Comment by Lukasss93** [comment]
Can you enable the debug flag in the nutgram config?

```php
$bot = new Nutgram('your-token', new Configuration(
    clientOptions: [
        'debug' => true,
    ],
));
```

What message does it give you?

**Comment by Lukasss93** [comment]
Reproduced with the help of a person in private.

This problem is caused by Laravel Herd:
https://github.com/beyondcode/herd-community/issues/169
(Nutgram uses http2 by default).

To solve the problem, do NOT use Laravel Herd OR disable http2 in Nutgram: 
https://nutgram.dev/docs/configuration/installation#enablehttp2
