### ISSUE TITLE
[FEATURE] How can i use this in php 8.1 ?!

### ISSUE THREAD

**Issue by Mobin-khorushi** [nutgram/nutgram#604]
### Is your feature request related to a problem? Please describe.

No i just want to use lower PHP version as my hosting limits !

### Describe the solution you'd like

is there any way other than installing older versions ?!

**Comment by sergix44** [comment]
You can use Nutgram with PHP 8.1, just not the version 4.x

Refer to the 3.x documentation instead of the 4.x
https://nutgram.dev/docs/3.x/configuration/installation
