### ISSUE TITLE
[BUG]  Is Handlers(that created by php artisan  nutgram:make:handler ) registered Automatically?

### ISSUE THREAD

**Issue by mtalaeii** [nutgram/nutgram#610]
### Nutgram version

latest

### PHP version

8.2.9

### Framework

Laravel

### Cache driver

mysql

### Describe the bug

So this is my handler code
```php
<?php

namespace App\Telegram\Handlers;

use SergiX44\Nutgram\Nutgram;

class Vardumper
{
    public function __invoke(Nutgram $bot): void
    {
        $bot->sendMessage('This is test handler are they load automatically?');
    }
}
```

my question is is it registered automatically?
This is my controller code
```php
<?php

namespace App\Http\Controllers;

use App\Telegram\Handlers\Vardumper;
use SergiX44\Nutgram\Nutgram;

class TelegramController extends Controller
{
    /**
     * Handle the telegram webhook request.
     */
    public function __invoke(Nutgram $bot)
    {
        $bot->onCommand('handler',Vardumper::class);
        $bot->run();
    }
}
```

### To Reproduce

1 . start the bot its ok
2 . use /handler command 
3 . there is no response from bot also we dont have any error and pending update in this case

### Expected behavior

Its better to load the handlers in 

> namespace App\Telegram\Handlers;

So users just put their handlers in this folders

**Comment by mtalaeii** [comment]
So its fixed by using telegram.php in routes :
```php
<?php
/** @var SergiX44\Nutgram\Nutgram $bot */

use App\Telegram\Handlers\Vardumper;
use SergiX44\Nutgram\Nutgram;

/*
|--------------------------------------------------------------------------
| Nutgram Handlers
|--------------------------------------------------------------------------
|
| Here is where you can register telegram handlers for Nutgram. These
| handlers are loaded by the NutgramServiceProvider. Enjoy!
|
*/

$bot->onCommand('start', function (Nutgram $bot) {
    $bot->sendMessage('Hello, world!');
})->description('The start command!');
$bot->onCommand('handler',Vardumper::class);
```
# but main issue is still there 
#### that i want all handler in this namespaces loaded automatically using psr-4 strategy

**Comment by Lukasss93** [comment]
See our documentation before opening issues: 
https://nutgram.dev/docs/usage/handlers#automatically-register-bot-commands

> that i want all handler in this namespaces loaded automatically using psr-4 strategy

We currently have no plans to add this feature. 
You should implement this feature on your own.
