### ISSUE TITLE
[BUG] onNewChatPhoto, onNewChatTitle... not working on channel

### ISSUE THREAD

**Issue by viiy** [nutgram/nutgram#611]
### Nutgram version

4.10.0

### PHP version

8.2

### Framework

laravel 

### Cache driver

Redis

### Describe the bug

onNewChatPhoto, onNewChatTitle and other similar handlers do not fire when events occur in the channel.
this happens because the update comes not in "message" attribute.

### To Reproduce

add bot to channel
add "route" $bot->onNewChatTitle(SomeHandler::class);
change channel title

### Expected behavior

handlers work with channels 

### Screenshots

![image](https://github.com/nutgram/nutgram/assets/917219/cdfd669d-1485-4584-b0ae-7c7704d95e8b)

**Comment by Lukasss93** [comment]
Update Nutgram to https://github.com/nutgram/nutgram/releases/tag/4.11.1

Add the `target` parameter to your handler:
```php
 $bot->onNewChatTitle(SomeHandler::class, UpdateType::CHANNEL_POST);
```
