### ISSUE TITLE
[BUG] Conversations don't work with polls

### ISSUE THREAD

**Issue by SaidkhojaIftikhor** [nutgram/nutgram#615]
### Nutgram version

3.17

### PHP version

8.1

### Framework

Laravel

### Cache driver

FileSystem

### OS

Ubunutu

### Dev environment

Nginx

### Describe the bug

Conversations don't work with polls

### To Reproduce

1. Create a conversation with several steps
2. Send a poll to user
3. After sending poll the conversation will end without performing the other steps
4. Maybe Nutgram doesn't receiving pollUpdate events 

### Expected behavior

The conversation should go to the next step after pollUpdate event but it won't

**Comment by Lukasss93** [comment]
Do you need to know the answer to the poll?

**Comment by ifedeev** [comment]
> Do you need to know the answer to the poll?

yes

**Comment by Lukasss93** [comment]
Why use polls inside conversations? It doesn't make much sense... 
Isn't it better to use a message with inline buttons?

Nutgram conversations do not support "updates" that do not have user id and chat id in their payload.
https://github.com/nutgram/nutgram/blob/5247bd18c7fdadd84065f76324504c8c63f5d1cc/src/Handlers/ResolveHandlers.php#L55-L59

**Comment by SaidkhojaIftikhor** [comment]
> Why use polls inside conversations? It doesn't make much sense... Isn't it better to use a message with inline buttons?

I have a quizzbot and I need to send polls step by step, it should be a conversation. Polls are better than quizzes with inline buttons

Why `$chatId` and `$userId` are required for conversation ?

**Comment by Lukasss93** [comment]
You can do it now. Update Nutgram to https://github.com/nutgram/nutgram/releases/tag/4.11.2 (you need PHP 8.2)

It works only with the following requirements:
- poll sent in PM
- poll type: quiz
- poll is_anonymous: false

This is an example of a QuizConversation:

```php
<?php
namespace App\Telegram\Conversations;

use SergiX44\Nutgram\Conversations\Conversation;
use SergiX44\Nutgram\Nutgram;

class QuizConversation extends Conversation
{
    protected ?string $pollId = null;
    protected int $correct = 0;

    public function start(Nutgram $bot)
    {
        $message = $bot->sendPoll(
            question: 'Do you like Nutgram?',
            options: ['Yes', 'No', 'Maybe'],
            is_anonymous: false,
            type: 'quiz',
            correct_option_id: 0,
        );
        $this->pollId = $message->poll->id;

        $this->next('secondStep');
    }

    public function secondStep(Nutgram $bot)
    {
        if(($bot->pollAnswer()?->poll_id === $this->pollId) && ($bot->pollAnswer()->option_ids[0] === 0)) {
            $this->correct++;
        }

        $message = $bot->sendPoll(
            question: 'Do you really like Nutgram?',
            options: ['Yes', 'No', 'Maybe'],
            is_anonymous: false,
            type: 'quiz',
            correct_option_id: 0,
        );
        $this->pollId = $message->poll->id;

        $this->next('thirdStep');
    }

    public function thirdStep(Nutgram $bot)
    {
        if(($bot->pollAnswer()?->poll_id === $this->pollId) && ($bot->pollAnswer()->option_ids[0] === 0)) {
            $this->correct++;
        }

        $bot->sendMessage("You answered correctly {$this->correct} times out of 2!");
        $this->end();
    }
}
``` 

Result:
![image](https://github.com/nutgram/nutgram/assets/4071613/18882045-2088-4fd2-b0b1-b98ddfe844bf)

**Comment by Lukasss93** [comment]
No, because you don't even get the update from telegram:
https://core.telegram.org/bots/api#pollanswer

> This object represents an answer of a user in a **non-anonymous** poll.
