### ISSUE TITLE
Pass additional data to conversation 

### ISSUE THREAD

**Issue by viiy** [nutgram/nutgram#616]
### Describe the solution you'd like

```php

class MyCoolConversation extends Conversation
{
    public function __construct(public readonly Model $model, string $string)
    {
    }
...



MyCoolConversation::begin($bot, null, null, $someModel, $someString);

```

**Comment by Lukasss93** [comment]
why would you do such a thing? what is the use case?

**Comment by viiy** [comment]
> why would you do such a thing? what is the use case?

this is necessary when the parameters of the conversation depend on the context. For example, we have a bot that implements surveys, and we need to pass the ID of a specific survey into the conversation. Or, we need to implement editing of some element, for example an article, we pass the model of this article to the conversation.
