### ISSUE TITLE
[BUG] Error when registering commands using the `registerMyCommands` method

### ISSUE THREAD

**Issue by windbridges** [nutgram/nutgram#618]
### Nutgram version

4.10

### PHP version

8.2

### Framework

Symfony 6.3

### Cache driver

ArrayCache

### OS

Ubuntu 22.04

### Dev environment

Docker

### Describe the bug

If I have multiple commands with the same name, I get an error `{"ok":false, "error_code":400, "description": "Bad Request: expected an Array of BotCommand"}` when calling `registerMyCommands()`. 

Multiple commands with the same names appear when optional parameters are needed - for example `start`, `start {parameter}`. That is, I need to handle the command both with and without a parameter. 

When Nutgram filters an array of commands before sending, then after array_unique() is executed, gaps between numbers appear in the array indexes, so when converting to json, the array is converted to an object instead of an array. This causes an error.

To fix it, just wrap the array_unique() call in array_values() to restore the index order.

### To Reproduce

```
        $nutgram
            ->onCommand('start', $this->startCommand->handle(...))
            ->description('The start command')
        ;

        $nutgram
            ->onCommand('start {startParameter}', $this->startCommand->handle(...))
            ->description('The start command')
        ;

        // It is importand to have third unique-named command to reproduce
        $nutgram
            ->onCommand('foo', $this->startCommand->handle(...))
            ->description('The foo command')
        ;
```

### Expected behavior

Successful request when registering commands

**Comment by SaidkhojaIftikhor** [comment]
Mine is working

![image](https://github.com/nutgram/nutgram/assets/77550379/3d57b100-2624-4fda-86d9-dcfb2e9f8cbe)

**Comment by SaidkhojaIftikhor** [comment]
Couldn't reproduce this bug, mine is working

![image](https://github.com/nutgram/nutgram/assets/77550379/31a83466-3e7f-42d5-99d0-3584de91fd7b)
