### ISSUE TITLE
[FEATURE] Intended 

### ISSUE THREAD

**Issue by viiy** [nutgram/nutgram#622]
just an idea.

When some route middleware is required, e.g. additional user data, we redirect the request, e.g. to the conversation.
After the conversation ends, we need to “redirect” the request to the intended route.

How i do it now 

```php
class IntendedService
{
    public static function store(Nutgram $bot): void
    {
        $bot->setUserData('intended', json_encode($bot->update()));
    }

    public static function proceed(Nutgram $bot): void
    {
        if ($intended = $bot->getUserData('intended')) {
            $intendedUpdate = $bot->getContainer()
                ->get(Hydrator::class)
                ->hydrate(json_decode($intended), Update::class);
            $bot->processUpdate($intendedUpdate);
            $bot->deleteUserData('intended');
        }
    }
}
```

```php
namespace App\Telegram\Middleware;
class PhoneNumberRequired
{
    public function __invoke(Nutgram $bot, $next): void
    {
        if (! Auth::user()->phone_number) {
            IntendedService::store($bot);
            PhoneNumberRequestConversation::begin($bot);
            return;
        }
        $next($bot);
    }
}
```
```php
namespace App\Telegram\Conversations;

class PhoneNumberRequestConversation extends Conversation
{
...
        $this->end();
        IntendedService::proceed($bot);
    }
}
```

You might find it useful to add this to your framework and release more elegantly =)

**Comment by sergix44** [comment]
Thats can be accomplished with the handler/middleware skipping inside the conversations: https://nutgram.dev/docs/usage/conversations#middleware
In this way, you can force a user to follow the conversation flow, with no escaping or other middleware interference.
That is useful like in your example if you want to trigger a registration flow like in your example for the first time a user is interacting with the bot.
