### ISSUE TITLE
[BUG] onPreCheckoutQuery Not Executing

### ISSUE THREAD

**Issue by dimafil1903** [nutgram/nutgram#624]
### Nutgram version

4.12.1

### PHP version

8.2

### Framework

Laravel

### Cache driver

Laravel+Redis

### OS

Ubuntu 22.04

### Dev environment

Docker

### Describe the bug

`$bot->onPreCheckoutQuery([InvoiceHandler::class, 'handle']);`

**The onPreCheckoutQuery function is intended to execute the handle method from the InvoiceHandler class when a pre-checkout query is received. However, for some reason, it does not work as expected, and the handle method is not being triggered when it should be.**

<img width="583" alt="Знімок екрана 2023-12-04 о 00 14 36" src="https://github.com/nutgram/nutgram/assets/25432951/ee2cfac3-9562-4dfa-88d7-7a8ea8017f17">

<img width="627" alt="Знімок екрана 2023-12-04 о 00 25 36" src="https://github.com/nutgram/nutgram/assets/25432951/9c422374-8e0f-4901-9905-b3c514ed9ffe">

**In the webhook method, I have implemented a manual check to handle the pre-checkout query and send a successful response. The code for this check looks as follows:**

<img width="932" alt="Знімок екрана 2023-12-04 о 00 21 42" src="https://github.com/nutgram/nutgram/assets/25432951/1ba342f8-b218-48c0-9936-5e74f2e00a36">

**This part of the code works as expected, and I receive a successful result when the pre_checkout_query is present.**

### To Reproduce

Just use it for payment functionality 

### Expected behavior

It should trigger handle method of class InvoiceHandler

**Comment by Lukasss93** [comment]
- Can you provide the full file registering all handlers?
- Have you already seen this [page](https://nutgram.dev/docs/usage/handlers#handlers-priority)?
- [Here ](https://github.com/Lukasss93/telegram-stickeroptimizer/blob/master/routes/telegram.php) you can find an example of payment functionality
