### ISSUE TITLE
Undefined variable $update in RunningMode/Webhook.php on line 74 [BUG] 

### ISSUE THREAD

**Issue by zinker402** [nutgram/nutgram#652]
### Nutgram version

4.4

### PHP version

8.2

### Framework

No Framework

### Cache driver

ArrayCache

### OS

Ubuntu

### Describe the bug

Undefined variable $update in vendor/nutgram/nutgram/src/RunningMode/Webhook.php on line 74

Uncaught Error: Call to a member function getType() on null in /vendor/nutgram/nutgram/src/RunningMode/Webhook.php:74 
 /vendor/nutgram/nutgram/src/Nutgram.php  SergiX44\\Nutgram\\RunningMode\\Webhook->processUpdates()  
 
 domain.uz/public_html/millionObunachiBot/index.php(315) SergiX44\\Nutgram\\Nutgram->run() in /vendor/nutgram/nutgram/src/RunningMode/Webhook.php on line 74 

PHP Warning:  Attempt to read property "value" on null in /vendor/nutgram/nutgram/src/Handlers/ResolveHandlers.php on line 73

### Expected behavior

to work properly

**Comment by sergix44** [comment]
Already fixed in later versions. Please update to the latest.
