### ISSUE TITLE
[BUG] Bulk Messenger just sending to one chat

### ISSUE THREAD

**Issue by superXdev** [nutgram/nutgram#654]
### Nutgram version

4

### PHP version

8.2

### Framework

No Framework

### Cache driver

Symfony

### OS

Ubuntu

### Describe the bug

I tried Bulk Messenger with this code

```php
$chats = ['', ''];

$bot->getBulkMessenger()
        ->setChats($chats)
        ->using(fn (Nutgram $bot, int $chatId) => $bot->sendMessage(text: 'test', chat_id: $chatId))
        ->startAsync();
```

But got error message after received one message from bot (only first account)

```
PHP Fatal error:  Uncaught Error: Invalid callback SergiX44\Nutgram\Support\BulkMessenger::handleAlarm, cannot access protected method SergiX44\Nutgram\Support\BulkMessenger::handleAlarm() in /media/fikri/78381B6A381B26A21/projects/client/ExcelDataBot/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:595
```

### To Reproduce

Using example code from Documentation on PHP 8.2

### Expected behavior

Working fine

**Comment by Lukasss93** [comment]
I can't reproduce the problem.
It works fine for me.
Can you create a public repository on github where this error occurs?

**Comment by sergix44** [comment]
Cannot reproduce it either, feel free to reopen if you can provide more details

**Comment by mahdi-hejazi** [comment]
it is because there is a bot id in your ids and bot cannot send message to bots or sometime for empty username that happen, and I don't know why?
