### ISSUE TITLE
[BUG] Cannot resolve 'SergiX44\Nutgram\Telegram\Types\WebApp\WebAppInfo'

### ISSUE THREAD

**Issue by Lukasss93** [nutgram/nutgram#656]
### Nutgram version

4.15.0

### PHP version

8.2

### Framework

Laravel

### Cache driver

Filesystem Cache

### OS

Linux (Debian)

### Dev environment

Apache + php-fpm

### Describe the bug

I got this exception:

**NotFoundException**
`Cannot resolve 'SergiX44\Nutgram\Telegram\Types\WebApp\WebAppInfo'`

### To Reproduce

Just use this method:

```php
$bot->sendMessage(
    text: 'test webapp',
    parse_mode: ParseMode::HTML,
    reply_markup: InlineKeyboardMarkup::make()->addRow(
        InlineKeyboardButton::make(
            text: 'open webapp',
            web_app: WebAppInfo::make('my-redacted-url),
        )
    ),
);
``` 

### Expected behavior

I expect no exception messages

**Comment by MaksOfVardi** [comment]
If run this code on pure PHP without Laravel framework, same error appear with еору same code as shownn: `Cannot resolve 'SergiX44\Nutgram\Telegram\Types\WebApp\WebAppInfo'. `
What is right way to open Mini Web Application via Inline Button ?

**Comment by Lukasss93** [comment]
Fixed in https://github.com/nutgram/nutgram/releases/tag/4.15.1
