### ISSUE TITLE
[BUG] Bulk message stops in first error

### ISSUE THREAD

**Issue by abbasudo** [nutgram/nutgram#660]
### Nutgram version

nutgram/laravel : ^1.3

### PHP version

8.2

### Framework

Laravel

### Cache driver

Filesystem

### OS

Linux

### Describe the bug

the bot skips other chats in case one chat produceses an error in bulk message function

### To Reproduce

the code :
```php
        $chats = User::all()->pluck('chat_id')->toArray();

        Telegram::getBulkMessenger()->setChats($chats)->setText('test')->startSync();
```

the error that caused the code to stop
```php
   SergiX44\Nutgram\Telegram\Exceptions\TelegramException 

  Forbidden: bot was blocked by the user
```

### Expected behavior

i expected the bot to ignore errors and keep sending messages to other chats

**Comment by Lukasss93** [comment]
You need to override the bulk logic using the `using` method:

```php
Telegram::getBulkMessenger()
	->setChats($chats)
	->setText('test')
	->using(function (Nutgram $bot, int|string $chatId): void {
		try{
			$bot->sendMessage(...[...$this->opt, 'chat_id' => $chatId, 'text' => $this->text]);
		} catch(Throwable) {
			//ignore errors
		}
	})
	->startSync();
```
