### ISSUE TITLE
[BUG] starting an inline conversation from custom step

### ISSUE THREAD

**Issue by abbasudo** [nutgram/nutgram#664]
### Nutgram version

nutgram/laravel : ^1.3

### PHP version

8.2

### Framework

Laravel 10.x

### Cache driver

Filesystem

### OS

Windows

### Describe the bug

got an exception when starting an inline conversation from custom step

```php
Error: Typed property SergiX44\Nutgram\Conversations\Conversation::$bot must not be accessed before initialization in D:\projects\telegram-bot\vendor\nutgram\nutgram\src\Conversations\Inlin
eMenu.php:262
```

### To Reproduce

```php
//telegram.php

$bot->onText('Subscription', [SubscriptionInline::class, 'secondStep']);

```

### Expected behavior

run the second step

**Comment by Lukasss93** [comment]
It's not a Nutgram bug. 
Conversations must start from the first step as written in the documentation.

You have 3 ways to solve this 'issue'.
1. Assign the `$bot` parameter to the `$this->bot` property. (It's a workaround. **Not recommended.**)
```php
//telegram.php
$bot->onText('Subscription', [SubscriptionInline::class, 'secondStep']);

//SubscriptionInline.php
//[...]
public function secondStep(Nutgram $bot)
{
    $this->bot = $bot;	// <== this
    $bot->sendMessage('Second step');
    $this->next('thirdStep');
}
//[...]
``` 
2. Extend your `SubscriptionInline` class and override the `$step` property.
```php
//telegram.php
$bot->onText('Subscription', SecondStepInSubscriptionInline::class);

//SecondStepInSubscriptionInline.php
class SecondStepInSubscriptionInlineextends Conversation
{
    protected ?string $step = 'secondStep';
}
``` 
3. Create a new conversation.
