### ISSUE TITLE
[BUG] "Serialization of 'Closure' is not allowed" when using Dependency Injection

### ISSUE THREAD

**Issue by PaulCombal** [nutgram/nutgram#668]
### Nutgram version

4.15.2

### PHP version

8.3.2-1

### Framework

Symfony 7.0.3

### Cache driver

any

### OS

Linux

### Describe the bug

```
Exception: Serialization of 'Closure' is not allowed in /home/paul/PhpstormProjects/x/vendor/nutgram/nutgram/src/Cache/ConversationCache.php:68
Stack trace:
#0 /home/paul/PhpstormProjects/x/vendor/nutgram/nutgram/src/Cache/ConversationCache.php(68): serialize()
#1 /home/paul/PhpstormProjects/x/vendor/nutgram/nutgram/src/Nutgram.php(251): SergiX44\Nutgram\Cache\ConversationCache->set()
```

When using autowiring of a service, repo, etc, in a Conversation Entity, the above Exception is thrown.

```php
<?php

namespace App\Telegram\Conversation;

use App\Repository\UserRepository;
use App\Service\UserService;
use SergiX44\Nutgram\Conversations\Conversation;
use SergiX44\Nutgram\Nutgram;

class RegisterBotRegisterConversation extends Conversation
{
    public function __construct( // Will work if there is no autowiring
        protected UserService $userService,
        protected UserRepository $userRepository
    )
    {
    }

    public string $username;
    public function start(Nutgram $bot)
    {
        $bot->sendMessage('value:');
        $this->next('validateUsername');
    }

    public function validateUsername(Nutgram $bot)
    {}
}
```

### To Reproduce

1. Create a new Conversation with 2 steps
2. Autowire a Service or EnityRepository into the conversation's __construct
3. launch the bot, and finish step 1 so that the Conversation has to be serialized
4. Error described as above

### Expected behavior

The conversation is serialized without errors, no exceptions thrown

### Additional context

I did a bit of debugging, and the type of $conversation in ConversationCache(68) is RegisterBotRegisterConversation in the example above.

**Comment by PaulCombal** [comment]
Adding precision, the issue seems to stem from the serialization of the EntityManager or generally Doctrine classes. Using __serialize alters the behavior. Injecting EntityManager or any Repository classes into the service is what causes the issue.

**Comment by sergix44** [comment]
Yeah as you found out, Nutgram can reinject at every step services that could be autowired.
Explained here in the symfony page: https://nutgram.dev/docs/configuration/symfony#enable-conversation-refresh
