### ISSUE TITLE
[BUG] Bot username regex

### ISSUE THREAD

**Issue by g-baranov** [nutgram/nutgram#670]
### Nutgram version

4.12.1

### PHP version

8.2

### Framework

Symfony

### Cache driver

Doctrine

### OS

Ubuntu

### Describe the bug

`$bot->onCommand('start', StartCommand::class);`
Handler will not work properly when bot command used in group chat like `start@MyHelloWorldBot`

Probably problem here:
<img width="546" alt="image" src="https://github.com/nutgram/nutgram/assets/16883506/76a5551e-1eb0-4bcb-b879-51f5472e772d">

https://github.com/nutgram/nutgram/blob/3a56cf2cd1b757b60dc9ec18e067dddbc869dd8e/src/Telegram/Types/Message/Message.php#L602

Bot username can contain upper case username. For example BotFather https://telegram.me/BotFather

### To Reproduce

1) Create a bot with username like MyHelloWorldBot
2) Add bot to telegram group
3) Register a handler that will handle /start command `$bot->onCommand('start', StartCommand::class);`
4) Type `start@MyHelloWorldBot` in group chat

Handler will not catch the message

### Expected behavior

Handler will catch the message

**Comment by Lukasss93** [comment]
Hi.
This is not a bug. The `i` flag means "insensitive". So it automatically takes uppercase.

You need to set the `botName` in your bot configuration:
https://nutgram.dev/docs/configuration/installation#botname
