### ISSUE TITLE
Is it possible to set default params value in sendMessage (and other methods) when bot init? [FEATURE] 

### ISSUE THREAD

**Issue by MaksOfVardi** [nutgram/nutgram#673]
### Is your feature request related to a problem? Please describe.

For example, all message I sent with parse_mode: ParseMode::HTML, I want to use default value ParseMode::HTML when parse_mode param ommited when sendMessage called.

**Comment by Lukasss93** [comment]
We will not do this because it would be difficult to maintain.

But you can always extend Nutgram:
https://nutgram.dev/docs/usage/extend

Example:

```php

Nutgram::macro('sendHtmlMessage', function (string $text) {
    return $this->sendMessage(
        text: $text,
        parse_mode: ParseMode::HTML,
    );
});

$bot->sendHtmlMessage('Hello');
```

**Comment by MaksOfVardi** [comment]
Thank you, this is really the solution I need!
