### ISSUE TITLE
[FEATURE] Passing parameters to the next step of conversation without setUserData and serialised in webhook mode

### ISSUE THREAD

**Issue by MaksOfVardi** [nutgram/nutgram#675]
### Is your feature request related to a problem? Please describe.

As documentation show I can passing parameters to a conversation when starting using data parameter:
```PHP
$bot->onCommand('start', function (Nutgram $bot) {
    StartConversation::begin($bot, data: [
        'name' => 'static name',
    ]);
});
```
as my conversation class described as follow:
```PHP
class StartConversation extends Conversation
{
    public function start(Nutgram $bot, string $name)
    {
        $bot->sendMessage("Hello $name");
        $this->next('secondStep');
    }
    public function secondStep(Nutgram $bot, string $name)
    {
        $bot->sendMessage("Another one hello for you, $name");
        $this->end();
    }
}
```
Yes, I can use set or setUserData method on $bot inside method, but signature of secondStep function reuqired two parameters to be passed (Nutgram $bot, string $name), and I won`t to write gettes inside function as I can pass it as arguments in method.

### Describe the solution you'd like

I need to pass parameters for the next step in calling next() method:
```PHP
    public function start(Nutgram $bot, string $name)
    {
        ...
        $this->next('secondStep', data:[
                'name' => 'value',
                // ....
        ]);
    }
```

**Comment by Lukasss93** [comment]
Documentation: 
https://nutgram.dev/docs/usage/conversations#creating-conversations

Examples:
https://github.com/Lukasss93/telegram-stickeroptimizer/tree/master/app/Telegram/Conversations

**Comment by MaksOfVardi** [comment]
Thanx, but neither the documentation nor the examples answers my question, how do I pass additional parameters to the called method specified in the next function in Conversation?
