### ISSUE TITLE
[BUG] Conversation does not store it's chat_id

### ISSUE THREAD

**Issue by sherwomeister** [nutgram/nutgram#679]
### Nutgram version

nutgram/symfony-bundle 1.1.0

### PHP version

8.2

### Framework

Symfony 7

### Cache driver

Doctrine DBAL

### OS

Ubuntu 22.04 LTS

### Describe the bug

$this->getChatId() returns null.

`request.CRITICAL: Uncaught PHP Exception TypeError: "SergiX44\Nutgram\Conversations\Conversation::getChatId(): Return value must be of type int, null returned" at Conversation.php line 187 {"exception":"[object] (TypeError(code: 0): SergiX44\\Nutgram\\Conversations\\Conversation::getChatId(): Return value must be of type int, null returned at /home/gigoshkin/Projects/CCAPI/vendor/nutgram/nutgram/src/Conversations/Conversation.php:187)"} []`

Also this error occurs when trying to begin new conversation after pressing inlineMenu's button:

```php
// SomeMenu extends InlineMenu

public function start(Nutgram $bot): void
{
    //...
}

public function someStep(Nutgram $bot): void
{
    SomeConversation::begin(...);
}



```

### To Reproduce

```php
<?php

//...

class SomeMenu extends InlineMenu
{

    public function start(Nutgram $bot, string $someId): void
    {

        $this->chatId = $this->getChatId(); // works fine

        $this->menuText('Menu Text', ['chat_id' => $this->getChatId()])
            ->addButtonRow(InlineKeyboardButton::make('Action', callback_data: "$someId@takeAction"))
            ->showMenu();
    }

    public function takeAction(Nutgram $bot)
    {
        $logId = $bot->callbackQuery()->data;

        //..

        $this->getChatId()

     //..

    }
}

```

### Expected behavior

...

**Comment by Lukasss93** [comment]
Please update your nutgram version to https://github.com/nutgram/nutgram/releases/tag/4.17.1
