### ISSUE TITLE
[BUG] Inline menu

### ISSUE THREAD

**Issue by flakka2022** [nutgram/nutgram#692]
### Nutgram version

last

### PHP version

8.2

### Framework

No Framework

### Cache driver

Redis

### OS

Windows

### Describe the bug

ChooseColorMenu example is broken . error Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message happen after trying to repeat select my chosen color .

### To Reproduce

1.use ChooseColorMenu  in the [Inline Menu Example](https://nutgram.dev/docs/usage/inline_menu)
2.double click on a color .
3. See error using onApiError method .

### Expected behavior

prevent error

**Comment by Lukasss93** [comment]
This is not a Nutgram issue.
Telegram will give you an error if you try to edit a message with the same content.

You have to find a way to fix this, for example you can save the state of the last button you pressed and do nothing if it is pressed again or you can close the conversation immediately or change the message after clicking the button...

**Comment by flakka2022** [comment]
it is possible please provide me an more complex example ? i think example inline menu is unclear .
