### ISSUE TITLE
sendMessage on replayed message in general topic always set message_thread_id

### ISSUE THREAD

**Issue by viiy** [nutgram/nutgram#699]
### Nutgram version

1.4

### PHP version

8.3

### Cache driver

Redis

### OS

ubuntu

### Dev environment

docker

### Describe the bug

Telegram setting message_thread_id as replay_message_id in general topic on replayed message, so when call $bot->sendMessage nutgram trying to send message to non-existent topic.

### To Reproduce

1. Add bot to group with forum
2. Send message to general topic
3. Replay to this message
4. Try to 
5. See log

### Expected behavior

Check `is_topic_message` on call sendMessage without message_thread_id

**Comment by Lukasss93** [comment]
I cannot reproduce this problem. Can you show me your code?

**Comment by viiy** [comment]
These are messages in a general topic
<img width="564" alt="S2JTuXRQwL" src="https://github.com/nutgram/nutgram/assets/917219/84c865d5-388a-46d4-8339-5355abb46c4c">

And these are two updates with these messages
<img width="161" alt="cLMMq1KFTo" src="https://github.com/nutgram/nutgram/assets/917219/27e179a8-91f7-4e9a-8e7d-431e81f3c13e">

So, this code 
```
$bot->onText('test1', function(Nutgram $bot){
   $bot->sendMessage('Ok'); 
});
```
will generate this update
![image](https://github.com/nutgram/nutgram/assets/917219/cebcbaf3-34aa-4599-854e-d151b6153028)

with replay from telegram api — Bad Request: message thread not found

**Comment by Lukasss93** [comment]
Fixed in https://github.com/nutgram/nutgram/releases/tag/4.19.2
