### ISSUE TITLE
[BUG] Implementation of server-side conversations can be tricky.

### ISSUE THREAD

**Issue by zoltes** [nutgram/nutgram#700]
### Nutgram version

4.19.1

### PHP version

8.2

### Framework

Laravel

### Cache driver

Filesystem

### OS

MacOS

### Dev environment

Docker + ngrok

### Describe the bug

Hello!
There is a closed task "starting inline conversation from server" [#663](https://github.com/nutgram/nutgram/issues/663)
The commited fix successfully passes tests but in real environment it gives the same original error "Bad Request: chat_id is empty"

### To Reproduce

1. php artisan nutgram:make:conversation StartConversation --menu

2. php artisan make:command InitStartConversationCommand

3. class InitStartConversationCommand

$bot = new Nutgram($_ENV['TELEGRAM_BOT_TOKEN']);

StartConversation::begin(
    bot: $bot, 
    userId: "12345", // I used a real hardcoded userId
    chatId: "12345"
);

### Expected behavior

there should be no exception when a conversation initiated from the server

### Screenshots

<img width="764" alt="Screenshot 2024-05-03 at 18 15 18" src="https://github.com/nutgram/nutgram/assets/11194456/b3ae6417-33e2-4891-a29d-489ffccce68b">

### Additional context

The Conversation works well when called using /command, but fails when it was initiated from the server.

**Comment by Lukasss93** [comment]
Hi, thanks for the feedback.
To make a conversation work server-side, see these examples:

### Conversation
```php
class BaseConversation extends Conversation
{
    public function start(Nutgram $bot): void
    {
        //when a server-side conversation is started,
        //the chatId parameter is not automatically filled by Nutgram
        //because we are not in an Update context.
        
        $bot->sendMessage(
            text: 'What is your name?',
            chat_id: $this->getChatId(), //so we need to set the chatId manually (only for this first step)
        );
        
        $this->next('getName');
    }
    
    public function getName(Nutgram $bot): void
    {
        $name = $bot->message()?->text ?? 'unknown';
        
        $bot->sendMessage("Hello, $name!");
        
        $this->end();
    }
}
``` 
![immagine](https://github.com/nutgram/nutgram/assets/4071613/0b957927-9d7c-43fe-9645-5a514a1415e2)

### InlineMenu
```php
class MenuConversation extends InlineMenu
{
    protected function doOpen(string $text, InlineKeyboardMarkup $buttons, array $opt): Message|null
    {
        //we need to override this method to set the chatId manually
        
        return $this->bot->sendMessage(...[
            'reply_markup' => $buttons,
            'text' => $text,
            'chat_id' => $this->chatId, //required for the first step
            ...$opt,
        ]);
    }
    
    public function start(Nutgram $bot): void
    {
        //when a server-side conversation is started,
        //the chatId parameter is not automatically filled by Nutgram
        //because we are not in an Update context.
        
        $this->chatId = $this->getChatId(); //so we need to set the chatId manually (only for this first step)
        
        $this->menuText('Message')
            ->addButtonRow(InlineKeyboardButton::make('Say hello', callback_data: "@hello"))
            ->addButtonRow(InlineKeyboardButton::make('Close', callback_data: "@end"))
            ->showMenu();
    }
    
    public function hello(Nutgram $bot): void
    {
        $bot->sendMessage('Hello');
        $this->end();
    }
    
    public function closing(Nutgram $bot): void
    {
        $bot->sendMessage('Bye!');
        parent::closing($bot);
    }
}
``` 
![immagine](https://github.com/nutgram/nutgram/assets/4071613/d62f44af-90a6-4a97-9db6-9fe51c3d3047)

## Small note
I know it is a bit confusing to make conversations work server-side. We will try to improve it.

**Comment by Lukasss93** [comment]
Released Nutgram https://github.com/nutgram/nutgram/releases/tag/4.20.0

**You will need to use the `$this->getChatId()` method if you want to use manual methods (sendMessage, etc...) in the first step of the conversation.**

To make a conversation work server-side, see these examples:

### Conversation
```php
class BaseConversation extends Conversation
{
    public function start(Nutgram $bot): void
    {
        $bot->sendMessage(
            text: 'What is your name?',
            chat_id: $this->getChatId(), // <--
        );
        $this->next('getName');
    }
    
    public function getName(Nutgram $bot): void
    {
        $name = $bot->message()?->text ?? 'unknown';
        $bot->sendMessage("Hello, $name!");
        $this->end();
    }
}
``` 

### InlineMenu
```php
class MenuConversation extends InlineMenu
{
    public function start(Nutgram $bot): void
    {
        $bot->sendMessage(
            text: 'Starting...',
            chat_id: $this->getChatId(), // <--
        );
        
        $this->menuText('Message')
            ->addButtonRow(InlineKeyboardButton::make('Say hello', callback_data: "@hello"))
            ->addButtonRow(InlineKeyboardButton::make('Close', callback_data: "@end"))
            ->showMenu();
    }
    
    public function hello(Nutgram $bot): void
    {
        $bot->sendMessage('Hello');
        $this->end();
    }
}
```
