### ISSUE TITLE
[BUG] $clientOpt argument in sendAttachment used only for requestMultipart, not for requestJson

### ISSUE THREAD

**Issue by deadsandro** [nutgram/nutgram#709]
### Nutgram version

4.19

### PHP version

8.2

### Framework

Laravel

### Cache driver

Laravel+Redis

### OS

Win

### Describe the bug

\SergiX44\Nutgram\Telegram\Client@sendAttachment

```
        if (is_resource($value) || $value instanceof InputFile) {
            ...
            return $this->requestMultipart($endpoint, [...$required, ...$opt], Message::class, $clientOpt);
        }

        return $this->requestJson($endpoint, [...$required, ...$opt], Message::class);
```

Options for Guzzle Client can't be set. 
For example, set request timeout for sendPhoto with url (string param).

i think requestJson method also should accept $clientOpt param

### To Reproduce

```
$bot->sendPhoto(
    $url,
    chat_id: $chatId,
    clientOpt: [
        'timeout' => 25
    ]
);
```

### Expected behavior

Guzzle waits 25 sec instead 5 sec

**Comment by Lukasss93** [comment]
You can change this parameter via Nutgram Configuration:
https://nutgram.dev/docs/configuration/installation#clienttimeout
