### ISSUE TITLE
[BUG] Timeout crashes on Polling Mode

### ISSUE THREAD

**Issue by PaulCombal** [nutgram/nutgram#715]
### Nutgram version

4.20.0

### PHP version

8.3

### Framework

Symfony

### Cache driver

Default

### OS

Linux

### Dev environment

Docker

### Describe the bug

I get this error fairly consistently out of the blue:

![image](https://github.com/nutgram/nutgram/assets/5382590/35b60aac-ac21-4783-b806-a6d5cd555450)

I guess my internet latency plays a role. From reading the error, I guess curl exits after waiting 1ms too much after the 11s delay. I would be interested in knowing if we can give curl a bit of extra time before crashing , just in case Telegram answers a few milliseconds late.

### To Reproduce

1. Start a bot in polling mode
2. Have latency
3. Wait..

### Expected behavior

The error is caught and the client tries again with another poll.

A crash can be expected if too many successive retries fail

**Comment by Lukasss93** [comment]
Just increase the polling timeout:
https://nutgram.dev/docs/configuration/installation#pollingtimeout
