### ISSUE TITLE
Laravel test DI issue

### ISSUE THREAD

**Issue by D1sho** [nutgram/nutgram#757]
Hi. When I'm trying to do same DI as described in documentation for Laravel testing.`$bot = app(Nutgram::class);` I'm getting this error. 
![image](https://github.com/user-attachments/assets/7b45c53e-79e6-4394-aae5-691614bf667f)
What could be the reason of it?

**Comment by sergix44** [comment]
Please reopen the issue following the issue template. If you are using Laravel, make sure to read the laravel package documentation first https://nutgram.dev/docs/configuration/laravel
