### ISSUE TITLE
[BUG] [WebHook] it goes into loop when it gives error

### ISSUE THREAD

**Issue by R0bbb** [nutgram/nutgram#760]
### Nutgram version

4.26.1

### PHP version

8.3.1

### Framework

No Framework

### Cache driver

Filesystem Cache

### OS

ubuntu

### Describe the bug

Whenever Telegram returns an error on a request like sending a message, the bot keeps getting the update and returns an error in an infinite loop

### To Reproduce

set webhook
send a request as sendMessage('test', '123') following a command

### Expected behavior

I expect it not to go into an infinite loop

**Comment by Lukasss93** [comment]
Missing information.
Closing the issue for now
