### ISSUE TITLE
[BUG] conversation not working

### ISSUE THREAD

**Issue by jaavid** [nutgram/nutgram#763]
### Nutgram version

 4.26.1

### PHP version

8.3.10

### Framework

No Framework

### Cache driver

FilesystemAdapter

### OS

Distributor ID:	Debian Description:	Debian GNU/Linux 11 (bullseye) Release:	11 Codename:	bullseye

### Describe the bug

conversation not going to the $this->next

how can I debug it?

### Expected behavior

conversation not going to the $this->next

**Comment by Lukasss93** [comment]
What type of run are you using? Polling or Webhook?
If you are using webhook, you will need to set up a persistent cache driver to use conversation:
https://nutgram.dev/docs/configuration/cache

**Comment by jaavid** [comment]
I was using a webhook with `FilesystemAdapter`, and after updating to version 4.27 and switching to **Redis**, the issue was resolved. It seems the problem was related to the `FilesystemAdapter`.
