### ISSUE TITLE
[BUG] Cannot use testing system when PhpUnit 11 is installed

### ISSUE THREAD

**Issue by andreich1980** [nutgram/nutgram#766]
### Nutgram version

4.27.0

### PHP version

8.2.19

### Framework

Laravel Framework 11.23.5

### Cache driver

database

### OS

Windows 11

### Dev environment

Laragon

### Describe the bug

> Error: Call to undefined method SergiX44\Nutgram\Testing\Constraints\ArraySubset::exporter()
> C:\Laragon\www\project\vendor\nutgram\nutgram\src\Testing\Constraints\ArraySubset.php:91
> C:\Laragon\www\project\vendor\nutgram\nutgram\src\Testing\Constraints\ArraySubset.php:107
> C:\Laragon\www\project\vendor\nutgram\nutgram\src\Testing\Constraints\ArraySubset.php:76
> C:\Laragon\www\project\vendor\nutgram\nutgram\src\Testing\Asserts.php:180
> C:\Laragon\www\project\vendor\nutgram\nutgram\src\Testing\Asserts.php:90
> C:\Laragon\www\project\vendor\nutgram\nutgram\src\Testing\Asserts.php:105
> C:\Laragon\www\project\vendor\nutgram\nutgram\src\Testing\Asserts.php:116
> C:\Laragon\www\project\tests\Feature\MyTest.php:17

### To Reproduce

Command registration

```php
// routes/telegram.php

/** @var SergiX44\Nutgram\Nutgram $bot */

$bot->onCommand('test', function(Nutgram $bot) {
    $bot->sendMessage('wrong-message');
});
```

Test (from the docs) https://nutgram.dev/docs/testing/asserting#example

```php
namespace Tests\Feature;

use SergiX44\Nutgram\Nutgram;
use Tests\TestCase;

class MyTest extends TestCase
{
    /**
     * @return void
     */
    public function test_bot()
    {
        $bot = app(Nutgram::class);
        $bot->hearText('/test')->reply()->assertReplyText('expected-message');
    }
}
```

Run the test and see the error.
If the expected message is equal to the actual message - the test is green.
If they are different - error:
> Error: Call to undefined method SergiX44\Nutgram\Testing\Constraints\ArraySubset::exporter()

### Expected behavior

When expected message is different from the actual message - the test should fail with understandable message: "Failed asserting that "wrong-message" is equal to "expected-message".

**Comment by Lukasss93** [comment]
> Should I provide a repo to reproduce the issue?
Yes, please.

**Comment by andreich1980** [comment]
@Lukasss93 
https://github.com/andreich1980/nutgram-laravel-testing
