### ISSUE TITLE
setRunningMode(Webhook::class)

### ISSUE THREAD

**Issue by mobinjavari** [nutgram/nutgram#777]
### Nutgram version

^4.17.0

### PHP version

8.2

### Framework

Laravel

### Cache driver

adk

### OS

Windows

### Dev environment

Laravel

### Describe the bug

---

Hi, I have a personal project in Laravel where I manage multiple bots simultaneously, so I store bot token information in the database.

I have a `Bot` model where I instantiate Nutgram like this:

```php
public function nutgram(): Nutgram
{
    if (!isset($this->nutgram))
        $this->nutgram = new Nutgram($this->token);

    return $this->nutgram;
}
```

Then I define a Laravel route as `/bot{token}/webhook`:

```php
$nutgram = $bot->nutgram();
$nutgram->setRunningMode(Webhook::class);
$nutgram->sendMessage(
//    "```\n" . (json_encode($request->all()) ?: 'False') . "```",
    "```\n" . ($nutgram->chat()?->id ?: 'False') . "```",
    chat_id: MY_CHAT_ID, 
    parse_mode: ParseMode::MARKDOWN
);
$nutgram->run();
```

The issue is that when I set the running mode to `Webhook`, I shouldn't need to provide the `chat_id` in `sendMessage`, as it should retrieve it from the update. However, this isn't happening.

No updates are detected, but when I manually check with `php://input` or `$request->all()`, I can see that the update is being sent to the server, but Nutgram doesn't recognize it.

--- 

### Expected behavior

```php
$nutgram = $bot->nutgram();
$nutgram->setRunningMode(Webhook::class);
$nutgram->sendMessage(
    "```\n" . ($nutgram->chat()?->id ?: 'False') . "```",
    parse_mode: ParseMode::MARKDOWN
);
$nutgram->run();
```
---
Telegram Send: MY_CHAT_ID

**Comment by sergix44** [comment]
- If you are using laravel, you want probably to extend the basic webhook mode like the laravel package does: https://github.com/nutgram/laravel/blob/master/src/RunningMode/LaravelWebhook.php
This ensure no matter if you are using octane, fpm, whatever you are always picking the request from the right place.
- Another thing the laravel package is doing for you is automatically loading the handlers on app boot: https://github.com/nutgram/laravel/blob/master/src/NutgramServiceProvider.php#L117
If you are not using it, you should load the handlers definitions yourself, so your method in your model should look soemething like this:
```php
public function nutgram(): Nutgram
{
    $bot = new Nutgram($this->token);
    require base_path('routes/telegram.php);
    return $bot;
}
```
